version: '3'
services:
   web:
      restart: always
      build:
          context: ..
          dockerfile: ./deployment/Dockerfile
      image: makeuoft-hardware-site:latest
      command: gunicorn main:flask_app --bind 0.0.0.0:8282
      ports:
         - "8282:8282"
      volumes:
         - ./application:/application
         - /var/run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock
      environment:
         - DB_USER_NAME=${DB_CREDENTIALS_USR}
         - DB_USER_PW=${DB_CREDENTIALS_PSW}
         - DB_NAME=${DB_NAME}
         - SECRET_KEY=${SECRET_KEY}
         - DB_SERVER=${DB_SERVER}
         - ENVIRONMENT=${ENVIRONMENT}
