"""empty message

Revision ID: 3e8cfda9e7f8
Revises: 
Create Date: 2019-08-19 20:33:07.558624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8cfda9e7f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parts_available',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_name', sa.String(length=255), nullable=False),
    sa.Column('part_manufacturer', sa.String(length=255), nullable=True),
    sa.Column('quantity_available', sa.Integer(), nullable=True),
    sa.Column('quantity_remaining', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_available_part_manufacturer'), 'parts_available', ['part_manufacturer'], unique=False)
    op.create_index(op.f('ix_parts_available_part_name'), 'parts_available', ['part_name'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_tag_name'), 'tag', ['tag_name'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts_signed_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_returned', sa.Boolean(), nullable=True),
    sa.Column('part_healthy', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.Column('part', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['part'], ['parts_available.id'], ),
    sa.ForeignKeyConstraint(['team'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts_available.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'part_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.Column('id_provided', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('parts_signed_out')
    op.drop_table('teams')
    op.drop_index(op.f('ix_tag_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_parts_available_part_name'), table_name='parts_available')
    op.drop_index(op.f('ix_parts_available_part_manufacturer'), table_name='parts_available')
    op.drop_table('parts_available')
    # ### end Alembic commands ###
